name: CI
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - pair:
            otp: 21.3
            elixir: 1.11.3
          - pair:
            otp: 22.2
            elixir: 1.12.3
          - pair:
            otp: 23.0
            elixir: 1.12.0
          - pair:
            otp: 24.0.6
            elixir: 1.12.3
          - pair:
            otp: 24.1.7
            elixir: 1.13.0
          - pair:
            otp: 24.2.1
            elixir: 1.13.3
          - pair:
            otp: 25.0.4
            elixir: 1.14.0
            otp: 25.2.1
            elixir: 1.14.3
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      # - run: mix test
      - run: mix coveralls.github


# jobs:
#   mix_test:
#     name: mix test (Erlang/OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - otp: 21.3.8.16
#             elixir: 1.10.0
#           - otp: 23.0.2
#             elixir: 1.10.0
#           - otp: 21.3.8.16
#             elixir: 1.10.3
#           - otp: 23.0.2
#             elixir: 1.10.3
#           - otp: 21.3.8.16
#             elixir: 1.11.2
#           - otp: 23.0.2
#             elixir: 1.11.2
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2.3.3
#       - uses: actions/setup-elixir@v1.4.2
#         with:
#           otp-version: '${{matrix.otp}}'
#           elixir-version: '${{matrix.elixir}}'
#       - name: Install Dependencies
#         run: |
#           mix local.rebar --force
#           mix local.hex --force
#           mix deps.get
#       - name: Run Tests
#         run: mix test
